---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debugger-daemon
  labels:
    app: debugger-daemon
spec:
  selector:
    matchLabels:
      app: debugger-daemon
  template:
    metadata:
      labels:
        app: debugger-daemon
    spec:
      serviceAccountName: debugger-sa
      hostNetwork: true
      hostPID: true
      securityContext:
        runAsUser: 0
      containers:
      - name: debugger
        image: registry.redhat.io/ubi8/ubi:latest
        command: ["/opt/scripts/entrypoint.sh"]
        args: ["daemon"]
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            - SYS_PTRACE
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: debugger-scripts
          mountPath: /opt/scripts
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
        - name: host-sys
          mountPath: /host/sys
          readOnly: true
        - name: host-dev
          mountPath: /host/dev
        - name: audit-logs
          mountPath: /var/log
        - name: host
          mountPath: /host
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: debugger-scripts
        configMap:
          name: debugger-scripts
          defaultMode: 0755
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-sys
        hostPath:
          path: /sys
      - name: host-dev
        hostPath:
          path: /dev
      - name: audit-logs
        hostPath:
          path: /var/log/debugger
          type: DirectoryOrCreate
      - name: host
        hostPath:
          path: /
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      tolerations:
      - operator: Exists