---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debugger-sa
  namespace: debugger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: debugger-sa
  annotations:
    description: "ClusterRole for debugger-sa with all required permissions"
rules:
# Cluster-scoped permissions
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: debugger-sa-binding
subjects:
- kind: ServiceAccount
  name: debugger-sa
  namespace: debugger
roleRef:
  kind: ClusterRole
  name: debugger-sa
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debugger-sa-binding-admin
  namespace: fttc-ancillary
subjects:
- kind: ServiceAccount
  name: debugger-sa
  namespace:  debugger
roleRef:
  kind: Role
  name: admin 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: debugger-sa-role
  namespace: debugger
  annotations:
    description: "Namespace scope Role for debugger-sa with all required permissions"
rules:
# Namespace-scoped permissions
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "patch"]
  resourceNames: ["debugger-audit-log", "debugger-access-control"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debugger-sa-role-binding
subjects:
- kind: ServiceAccount
  name: debugger-sa
  namespace: debugger
roleRef:
  kind: Role
  name: debugger-sa-role
  apiGroup: rbac.authorization.k8s.io
 