---
apiVersion: batch/v1
kind: Job
metadata:
  name: debugger-job-TIMESTAMP
  namespace: fttc-ancillary
  labels:
    app: debugger-job
    user: "USER_PLACEHOLDER"
spec:
  ttlSecondsAfterFinished: 3600  # Clean up after 1 hour
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: debugger-job
        user: "USER_PLACEHOLDER"
    spec:
      serviceAccountName: debugger-sa
      restartPolicy: Never
      hostNetwork: true
      hostPID: true
      securityContext:
        runAsUser: 0
      nodeSelector:
        kubernetes.io/hostname: "NODE_PLACEHOLDER"
      containers:
      - name: debugger
        image: registry.redhat.io/ubi8/ubi:latest
        command: ["/opt/scripts/entrypoint.sh"]
        args: ["COMMAND_PLACEHOLDER"]
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            - SYS_PTRACE
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: REMOTE_USER
          value: "USER_PLACEHOLDER"
        volumeMounts:
        - name: debugger-scripts
          mountPath: /opt/scripts
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
        - name: host-sys
          mountPath: /host/sys
          readOnly: true
        - name: host-dev
          mountPath: /host/dev
        - name: audit-logs
          mountPath: /var/log
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: debugger-scripts
        configMap:
          name: debugger-scripts
          defaultMode: 0755
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-sys
        hostPath:
          path: /sys
      - name: host-dev
        hostPath:
          path: /dev
      - name: audit-logs
        hostPath:
          path: /var/log/debugger
          type: DirectoryOrCreate