# The actual Kyverno policy definition to be referenced by the PolicyGenerator
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-scc-by-deployment-and-image
  annotations:
    policies.kyverno.io/title: Restrict SCC by Deployment and Image
    policies.kyverno.io/category: Security, PSP
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy restricts the use of specific SecurityContextConstraints (SCC)
      to only be allowed for specific deployments with specific container images.
      It helps prevent privilege escalation by ensuring only authorized workloads
      can use privileged SCCs.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-scc-annotations
      match:
        any:
        - resources:
            kinds:
              - Pod
      preconditions:
        all:
        # Only apply this rule if the pod has the SCC annotation
        - key: "{{request.object.metadata.annotations.\"openshift.io/scc\"}}"
          operator: Equals
          value: "{{request.object.metadata.annotations.\"openshift.io/scc\"}}"
      validate:
        message: "The SCC '{{request.object.metadata.annotations.\"openshift.io/scc\"}}' can only be used by authorized deployments and images."
        deny:
          conditions:
            all:
            # Checks if using the restricted SCC (customize this value)
            - key: "{{request.object.metadata.annotations.\"openshift.io/scc\"}}"
              operator: Equals
              value: "privileged"
            # Checks if NOT an authorized deployment (customize these values)
            - key: "{{ request.object.metadata.ownerReferences[0].name }}"
              operator: NotIn
              value: 
              - "splunk-universal-forwarder"
              - "debugger-job"
            # Checks if NOT using an authorized image (customize these values)
            - key: "{{ images.contains(@, 'splunk/universalforwarder:*') || images.contains(@, 'debugger:*') }}"
              operator: Equals
              value: false
